version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: savory_postgres
    environment:
      POSTGRES_USER: savory
      POSTGRES_PASSWORD: savory123
      POSTGRES_DB: savory_db
    ports:
      - "5432:5432"
    volumes:
      - savory_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: savory_redis
    ports:
      - "6379:6379"
    volumes:
      - savory_redis_data:/data

volumes:
  savory_pg_data:
  savory_redis_data:
